docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - 'Zend Framework 3':
    - 'Getting Started': https://docs.zendframework.com/tutorials/getting-started/overview/
    - Tutorials: https://docs.zendframework.com/tutorials/
  - 'Zend Framework 2':
    - 'Getting Started': https://framework.zend.com/manual/2.4/en/user-guide/overview.html
    - 'Reference Guide': https://framework.zend.com/manual/2.4/en/index.html
    - API: https://framework.zend.com/docs/api/zf2
  - 'Zend Framework 1':
    - 'Getting Started': https://framework.zend.com/manual/1.12/en/learning.quickstart.html
    - 'Reference Guide': https://framework.zend.com/manual/1.12/en/manual.html
    - API: https://framework.zend.com/docs/api/zf1
site_name: 'Zend Framework Documentation'
site_description: 'Documentation for the MVC Framework, Expressive, and all Components'
extra:
  show_special_homepage: true
