docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - 404.md
site_name: ZF Docs
site_description: 'Documentation for the ZF components'
repo_url: 'https://github.com/zendframework/zendframework.github.io'
copyright: 'Copyright (c) 2015-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
extra_css:
    - css/site.css
